name: worknest

services:
  server:
    build:
      context: ./server
      target: dev
    container_name: worknest-server-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5500
    env_file:
      - ./server/.env
    ports:
      - "5500:5500"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - backend

  client:
    build:
      context: ./client
      target: build
    container_name: worknest-client-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - backend
    environment:
      VITE_API_TARGET: http://server:5500
    depends_on:
      - server
    command: npm run dev -- --host

networks:
  backend:
    driver: bridge
